[project]
name = "speech-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gtts>=2.5.4",
    "pydub>=0.25.1",
    "pyttsx3",
    "snowflake-id",
    "soundfile",
    "speechrecognition>=3.14.3",
]
